print ("")
print ("(prima di calcolare il prezzo del gas ricorda che se devi inserire un numero decimale devi mettere il punto e non la virgola)")
print ("")
sp = float(input("scatti nella bolletta precedente: "))
sa = float(input("scatti sul contatore: "))
cs = float(input("costo singolo scatto: "))
ca = float(input("canone fisso: "))
print ("")
tot = ca+(cs*(sp+sa))
print ("questo trimestre hai pagato", tot, "euro")
