import scacchi_strani

c_board = board()

wk = king(5, 8, "w", c_board)
wq = queen(4, 8, "w", c_board)
wr1 = rook(1, 8, "w", c_board)
wr2 = rook(8, 8, "w", c_board)
wb1 = bishop(3, 8, "w", c_board)
wb2 = bishop(6, 8, "w", c_board)
wh1 = knight(2, 8, "w", c_board)
wh2 = knight(7, 8, "w", c_board)
wp1 = pond(1, 7, "w", c_board)
wp2 = pond(2, 7, "w", c_board)
wp3 = pond(3, 7, "w", c_board)
wp4 = pond(4, 7, "w", c_board)
wp5 = pond(5, 7, "w", c_board)
wp6 = pond(6, 7, "w", c_board)
wp7 = pond(7, 7, "w", c_board)
wp8 = pond(8, 7, "w", c_board)

bk = king(4, 1, "b", c_board)
bq = queen(5, 1, "b", c_board)
br1 = rook(1, 1, "b", c_board)
br2 = rook(8, 1, "b", c_board)
bb1 = bishop(3, 1, "b", c_board)
bb2 = bishop(6, 1, "b", c_board)
bh1 = knight(2, 1, "b", c_board)
bh2 = knight(7, 1, "b", c_board)
bp1 = pond(1, 2, "b", c_board)
bp2 = pond(2, 2, "b", c_board)
bp3 = pond(3, 2, "b", c_board)
bp4 = pond(4, 2, "b", c_board)
bp5 = pond(5, 2, "b", c_board)
bp6 = pond(6, 2, "b", c_board)
bp7 = pond(7, 2, "b", c_board)
bp8 = pond(8, 2, "b", c_board)

c_board.draw()
